name: ramp-meg
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scikit-learn>=0.22
  - scipy
  - click
  - pandas
  - matplotlib

  # Extra requirements
  - tensorflow-gpu
  - pytorch
  - keras
  - lightgbm

  - pip
  - pip:
    - osfclient
    - ramp-workflow
    - ramp-utils

    # Extra requirements pip
    - xgboost
    - catboost

